# This is a basic workflow to help you get started with Actions

name: hugo blog deploy1

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #1. 가상머신으로 checkout
      - uses: actions/checkout@v2

      #2. theme를 submodule로 등록했는데 그것도 checkout
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          # run 다음 내용들은 submodule을 최신으로 udapte한것을 가져오는 내용 + a이다.
          
     #3. npm install 사용하는 theme가 sass/scss를 사용하는 경우 node.js를 설치하고 npm install 과정이 필요하다.
      - name: npm install
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
        
      #4. Hugo 설치 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
        
      #5. build (public 폴더에 저장 된다.)
      - name: Build Hugo Site
        run: |
          hugo --minify
         # minify는 압축시키는 것을 의미한다. 
    
      #6.Deploy 배포: git token이 필요하다. gh-pages로 publish하는 것 잊지 말자 
      #public 폴더를 github page의 gh-pages 브챈치에 배포한다는 의미이다. 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
